---
title: "大语言模型编年史：从Transformer到ChatGPT的AI革命"
creator:
  - role: author
    text: "AI History Chronicler"
language: zh-CN
rights: "© 2025 AI History Chronicler. All rights reserved."
publisher: "Self-Published"
date: "2025-10-19"
cover-image: "assets/images/cover.svg"
description: |
  一部全面记录大语言模型发展历史的编年史，从2017年Transformer论文到2025年的ChatGPT时代，
  涵盖技术创新、公司竞争和行业变革的完整故事。
subject:
  - "人工智能"
  - "大语言模型"
  - "ChatGPT"
  - "深度学习"
  - "科技历史"
---
